### ISSUE TITLE
1.6.2 内存泄漏问题

### ISSUE THREAD

**Issue by toohamster** [SeasX/SeasLog#103]
![seaslog0 1](https://cloud.githubusercontent.com/assets/16458414/18039869/867f96f2-6dd9-11e6-8d19-3bc07d041a08.png)

PHP 版本 5.40,

**Comment by Neeke** [comment]
@toohamster   请使用Master版本测试一下，版本号为 1.6.4

**Comment by Neeke** [comment]
Fixed with 1.6.8
