### ISSUE TITLE
TCP方式,是每次都重连吗?

### ISSUE THREAD

**Issue by km3945** [SeasX/SeasLog#104]
TCP方式,是每条记录都重连吗?

**Comment by Neeke** [comment]
如果使用了buffer，会在满足buffer_size或请求结束时，连接发出；
如果没有使用buffer，是每次都重连。

**Comment by lgctc123** [comment]
我使用TCP，会出现分包的情况，请问怎么才能避免分包呢

**Comment by huanyangchen** [comment]
测试过程中设置了buffer_size，tcp接收最后一条log不完整，同问怎样避免分包呢

**Comment by Neeke** [comment]
@km3945  重连问题已经在修复 #142 时一并解决。
