### ISSUE TITLE
V1.6.2 phpinfo() -> Warning: Unknown: Permission denied in Unknown on line 0

### ISSUE THREAD

**Issue by SparkLee** [SeasX/SeasLog#105]
![image](https://cloud.githubusercontent.com/assets/7686363/18423244/0ac70ee8-78d6-11e6-884c-5fb088870b00.png)

![image](https://cloud.githubusercontent.com/assets/7686363/18423255/251a40d0-78d6-11e6-9887-a5cfd50b1d2b.png)

**Comment by Neeke** [comment]
请确保日志目录有读写权限

**Comment by SparkLee** [comment]
确实是日志目录的权限问题，非常感谢Neeke.
