### ISSUE TITLE
analyzerCount统计日志所有行数不准确

### ISSUE THREAD

**Issue by indextank** [SeasX/SeasLog#106]
![image](https://cloud.githubusercontent.com/assets/6389841/19829879/c5b42a2a-9e1e-11e6-8f45-3ae56d03ad6d.png)
![image](https://cloud.githubusercontent.com/assets/6389841/19829880/caba4ed2-9e1e-11e6-8515-acf492451554.png)
使用analyzerCount统计日志所有行数的时候，结果不对；
有的时候正常，有的时候不对。。但是日志文件中末尾总是会多一行空格，因此每次统计的时候，都会把空行算成一个，也就是总是多了一个。。但是上面的不知道为什么，结果就不对了

**Comment by Neeke** [comment]
analyzerCount是利用管道进行more统计，统计info数量的时候，执行的是这条命令：

more /var/log/www/default/info.* 2>/dev/null| grep 'info' -wc

可通过该命令统计执行一下，看看结果

**Comment by Neeke** [comment]
图1中，一个exception打了两行，因此统计时少统计了值，不是统计行数，而是统计critical的出现次数；
即，不是28行日志，而是28个critical
