### ISSUE TITLE
使用analyzerDetail取出指定范围id的结果不对！

### ISSUE THREAD

**Issue by indextank** [SeasX/SeasLog#107]
![image](https://cloud.githubusercontent.com/assets/6389841/19829937/46a36c3a-9e20-11e6-8d77-c405bfea0980.png)
![image](https://cloud.githubusercontent.com/assets/6389841/19829940/535b954c-9e20-11e6-9971-18c08cca1090.png)

我估摸着这2个种情况，应该是有关联的！

**Comment by Neeke** [comment]
与 #106  相关
