### ISSUE TITLE
是否可以考虑Buffer部分再做些优化，例如加入Buffer Size

### ISSUE THREAD

**Issue by devtoby** [SeasX/SeasLog#11]
看到最近的两次commit，对此项目来说意义很大啊。

是否可以考虑增加Buffer Size选项来控制刷新到文件的时机，因部分复杂的项目在日志记录泛滥的情况下，所有日志都在内存中只进行一次刷新，是否再此过程中会导致内存占用过多的情况。

**Comment by Neeke** [comment]
很好的建议。在下个小版本中将添加buffer size配置

**Comment by Neeke** [comment]
感谢反馈，很好的想法。将在下个小版本中实现。

在 2014年7月29日 下午11:21，Jerry Yang notifications@github.com写道：
