### ISSUE TITLE
php7.1的问题

### ISSUE THREAD

**Issue by pansmaze** [SeasX/SeasLog#111]
seaslog.appender = 1                                    ;日志存储介质 1File 2TCP 3UDP (默认为1)/
这个选1，或者3
windows下
PHP版本 php-7.1.0-Win32-VC14-x64
seaslog最新版 http://pecl.php.net/package/SeasLog/1.6.8/windows

打不出任何log，请看一看

**Comment by Neeke** [comment]
感谢反馈，请优先使用Linux系统
