### ISSUE TITLE
文档中的压测结果是怎样实现的

### ISSUE THREAD

**Issue by huanyangchen** [SeasX/SeasLog#112]
最近在评估seaslog是否能用在自己的项目中，性能是考虑的最重要因素。

看到文档中压测qps最高可达到8000，然后自己安装试着压测了一下。我的压测方式是这样的，在自己的项目根目录下新建文件 test_seaslog.php ，然后文件中只有一句代码：SeasLog::err("this is a error log");
使用工具压测 http_load -p 200 -t 10 http://host/test_seaslog.php
不管我怎么提高并发，压测最高qps都没有超过2000，我的机器配置是Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz ，双核 ，centos

感觉这种方式不能够真实的测试出seaslog的性能，请问下作者具体的压测方式？非常感谢~

**Comment by Neeke** [comment]
请问，你是使用什么web server？

**Comment by Neeke** [comment]
@huanyangchen 

这里有一份新的性能测试结论
https://www.oschina.net/news/96207/seaslogger-0-1-2-released
