### ISSUE TITLE
log format 目前过于单调，建议增加format选项来控制输出

### ISSUE THREAD

**Issue by devtoby** [SeasX/SeasLog#12]
对于web服务来说，请求的URL、Method所执行File line对于检查系统可能存在的问题来说意义重大，建议增加这些选项作为format的可定制参数，如果这么做了，同时请考虑cli下的记录

**Comment by sharmy** [comment]
建议日志中的datetime部分支持显示毫秒部分,在日志量比较多的时候我们想看看某些请求处理时间等比较有用

**Comment by Neeke** [comment]
建议很好.  目前SeasLog已经提供了时间戳,并具体到毫秒部分．

log格式统一为： {type} | {pid} | {timeStamp} |{dateTime} | {logInfo}

error | 23625 | 1406422432.786 | 2014:07:27 08:53:52 | this is a error
test by log
debug | 23625 | 1406422432.786 | 2014:07:27 08:53:52 | this is a neeke debug

在 2015年9月24日 上午9:43，sharmy notifications@github.com写道：

**Comment by zhaochunyang** [comment]
log里记录的content要去哪里看

**Comment by Neeke** [comment]
content已经与message进行匹配合并。可基于此机制，较自由地定义日志内容格式。

2015-12-09 17:27 GMT+08:00 zhaochunyang notifications@github.com:
