### ISSUE TITLE
2 (TCP) or 3 (UDP) 时，有做数据压缩吗，有重试吗？

### ISSUE THREAD

**Issue by vus520** [SeasX/SeasLog#122]
现在想通过SeasLog做日志中心化，需要将每台机器的日志收集到异地汇总，需要对数据进行远程传输。

现在SeasLog有下面两个功能吗？
1，压缩
2，失败缓存，并重试

**Comment by Neeke** [comment]
你好，目前这两个功能暂无。
后续将作升级丰富，也欢迎你提交PR。

**Comment by Neeke** [comment]
@vus520   近期将安排升级
期望使用的压缩方式是什么？

**Comment by vus520** [comment]
一般都是gzip，对用户透明，用户不需要去做gzip压缩，是你直接在扩展里做，暴露一个参数即可

**Comment by Neeke** [comment]
明确

**Comment by hushulin** [comment]
@Neeke 作者大大，你好。这个issue 计划什么时候开发完？

**Comment by Neeke** [comment]
@vus520  异地汇总的机器不存在于内网，而是外网？
