### ISSUE TITLE
请问如何修改默认输出在日志文件里面的格式

### ISSUE THREAD

**Issue by DemonFengYuXiang** [SeasX/SeasLog#123]
你好,我打算使用seaslog用到我的项目,然后,我看了一下文档,说日志格式统一是 

error | 23625 | 1406422432.786 | 2014:07:27 08:53:52 | this is a error test by log
debug | 23625 | 1406422432.786 | 2014:07:27 08:53:52 | this is a neeke debug
info | 23625 | 1406422432.787 | 2014:07:27 08:53:52 | this is a info log
notice | 23625 | 1406422432.787 | 2014:07:27 08:53:52 | this is a notice log 

但是,我不想这样输出,我想这样输出: 
[2014:07:27 08:53:52]:ERROR  this is a error test by log 
[2014:07:27 08:53:52]:DEBUG this is a neeke debug  

请问如何进行设置?? 

还有我只是日志级别在seaslog划分了很多,但是,我只知道debug \ info \ error \ warning是什么时候调用,但是我不清楚alert \ critical这些级别的具体含义

**Comment by Neeke** [comment]
你好，目前还不支持格式的自定义。如果自定义格式需求强烈，后续版本会提供此功能。

级别定义，可以搜索了解“PSR-3”规范。

**Comment by Neeke** [comment]
日志格式自定义已经在1.7.5版本支持。
