### ISSUE TITLE
按文件size来切分日志文件是否可行?

### ISSUE THREAD

**Issue by laomagege** [SeasX/SeasLog#124]
目前只有按类型切分, 按hour/day, 但是理论上按文件大小切分比较好.
是不是按文件大小切分日志会导致性能问题(每次或者每一批次要检查文件大小)?
如果是这样,是否可以采用按日志条数来切分文件呢? 这样处理的时候会比较简单吧,只要每个文件加一个计数器,没写一条计数++, 到了设定值,就换新文件,同时日志计数归零.

**Comment by MerlinFeng** [comment]
用shell切分文件--split 行数 大小

**Comment by laomagege** [comment]
1. 在shell切分之前,就已经按每天一个文件切分了
2. shell的切分时可能和写日志有冲突, 也不是太好

**Comment by Neeke** [comment]
按文件大小切分，则意味着要不停地进行stat/du操作，以获取文件大小
可以考虑，但会影响性能。

**Comment by Neeke** [comment]
暂不考虑按文件大小分日志文件。
