### ISSUE TITLE
cli模式文件句柄无法复用

### ISSUE THREAD

**Issue by tttlkkkl** [SeasX/SeasLog#126]
在一个nsq轮询服务中用seaslog做日志输出报错Warning: SeasLog::debug(/www/log/nsq_nsqCommon/20170324.log): failed to open stream: Too many open files in /mnt/shared/www/swoole-nsq/lib/framework/log/Log.php on line 143

**Comment by Neeke** [comment]
问题收到。将在下一个版本修复。

**Comment by Neeke** [comment]
有没有开启 use_buffer ？

**Comment by Neeke** [comment]
将在 #142  中进行修复
