### ISSUE TITLE
1.6.9 .tgz包不能安装在php5.6上吗？

### ISSUE THREAD

**Issue by Purelightme** [SeasX/SeasLog#127]
![2017-03-31 7 53 37](https://cloud.githubusercontent.com/assets/16385534/24549422/c5803b20-164b-11e7-904d-18615902168b.png)
这个怎么解决？

**Comment by pkuzzw** [comment]
这个我刚遇到过，应该是你系统有多个版本的PHP，造成版本不一致，主要在./configure的时候添加--with-php-config选项，配置正确的php-config，最好删除一个PHP版本，PS：很可能一个是YUM安装的，一个是源码安装的
