### ISSUE TITLE
请问seaslog的日志格式有办法弄成json格式的吗？还有，能否直接将日志发往ELK

### ISSUE THREAD

**Issue by zwjzxh520** [SeasX/SeasLog#128]
主要是seaslog，会有个默认的【 logtype | 】这样的格式定义，不知道要怎么样才能让它以json的形式保存。

seaslog是直接TCP发送日志的，但是不知道是否能直接接入ELK呢？

**Comment by Neeke** [comment]
问题1:  json形式，指的是整条日志，以json保存？

问题2: 可以直接接入ELK

**Comment by Neeke** [comment]
问题2回答补充：
可以通过appender和remote_host、remote_port的设定，发往rsyslog server，由rsyslog server对接ELK完成对接需求。

**Comment by zwjzxh520** [comment]
好的，谢谢。主要是希望能直接发送json格式的数据
