### ISSUE TITLE
SeasLog::setLogger

### ISSUE THREAD

**Issue by km3945** [SeasX/SeasLog#129]
在文件开头设置了模块
SeasLog::setLogger(SYS_MODULE);

但是错误信息的异常信息还是记录到了default里. 这是否正常.
按我的理解或需要.我即设置了模块.那他的信息所有类型日志就应进入该模块.

**Comment by Neeke** [comment]
错误和异常，记录至default中，是即定的设计。

可以讨论是否对设计进行更改。

**Comment by Neeke** [comment]
该问题已经修复。
需注意一点：当PHP出现语法错误时，可能仍然记录在default中，因为语法解析抛出的错误，可能在setLogger命令执行之前。
