### ISSUE TITLE
日志超过万条统计总数和读取日志分页就很慢

### ISSUE THREAD

**Issue by suruibuas** [SeasX/SeasLog#133]
SeasLog::analyzerCount(SEASLOG_INFO, $file);

日志行数如果超过万条的话，速度就慢

**Comment by Neeke** [comment]
SeasLog中`analyzerCount`函数目前使用的是more 、grep、wc命令管道进行统计，如果出现日志过大，是存在缓慢问题的，此处有优化空间。
