### ISSUE TITLE
支持 TCP、UDP 发送？

### ISSUE THREAD

**Issue by xpader** [SeasX/SeasLog#135]
只看到官方说支持 TCP、UDP 发送到某个集中的服务器，但找遍了所有的东西，没有任何文章、文档来说明这里到底是怎么使用的，无论我是对本机，还是在另外一台机器安装了，然后在本地设上目标机器的IP，都报连接被拒绝。

有具体的文档说明这是怎么用的吗？

**Comment by qzfzz** [comment]
你需要syslog-ng之类的日志服务器提供服务才可以使用tcp或udp接收日志

**Comment by Neeke** [comment]
请使用rsyslog server或syslog-ng来搭建日志收集Server。
