### ISSUE TITLE
日志设置为 /tmp/SeasLog 时，无写入权限

### ISSUE THREAD

**Issue by hi-man** [SeasX/SeasLog#136]
配置如下：
extension = seaslog.so                                                                                                   
seaslog.default_basepath = /tmp/SeasLog    ;默认log根目录                                                                
seaslog.default_logger = default                ;默认logger目录                                                          
seaslog.disting_type = 0                        ;是否以type分文件 1是 0否(默认)                                          
seaslog.disting_by_hour = 0                     ;是否每小时划分一个文件 1是 0否(默认)                                    
seaslog.use_buffer = 0                          ;是否启用buffer 1是 0否(默认)                                            
seaslog.buffer_size = 0                       ;buffer中缓冲数量 默认0(不使用buffer_size)                                 
seaslog.level = 0                               ;记录日志级别 默认0(所有日志) 

服务器启动时，系统服务自动创建/tmp/SeasLog，目录所属用户为root, 用户组为root
php-fpm运行时用户为www，由于不具备权限，无法将日志写入/tmp/SeasLog

**Comment by Neeke** [comment]
在服务启动前，先手动创建basepath目录吧，并赋属主和读写权限。
或可使用tcp或udp的appender.
