### ISSUE TITLE
analyzerDetail中的排序不能倒序排

### ISSUE THREAD

**Issue by alongken2005** [SeasX/SeasLog#137]
排序用SEASLOG_DETAIL_ORDER_DESC 就不显示结果了，好像是个bug

**Comment by energytank** [comment]
这个现在有解决了吗？倒序的问题。

**Comment by Neeke** [comment]
请问，是在什么系统版本情况下，用的哪个版本PHP ？
另可附重现case否？

**Comment by otaku-it** [comment]
您好，
我用的是SeasLog-1.7.0、SeasLog-1.6.9版本，php5.5、php5.6版本，我测试了下，在unix下analyzerDetail这个方法是不能倒序的，linux下可以，现在又出现了几个新问题，1、analyzerCount统计方法第一个参数填写all查所有，第二参数填写date('Ymd',time())查不出来，不能查当天所有的日志，只能当个类型的日志查；2、analyzerCount方法第三个参数用关键词查，不能模糊查询，analyzerDetail方法同理也不能模糊查询。

在 2017-07-31 15:45:36，"Neeke Gao" <notifications@github.com> 写道：


请问，是在什么系统版本情况下，用的哪个版本PHP ？

**Comment by Neeke** [comment]
可否提供一个重现case，方便更快地进行修复

**Comment by Neeke** [comment]
注意：倒排需要系统tac命令支持。
如果没有tac命令，将不支持倒排功能。
