### ISSUE TITLE
SeasLog::info(): File exists

### ISSUE THREAD

**Issue by Code-Ken** [SeasX/SeasLog#138]
用Seaslog写日志的时候,有时候会报错SeasLog::info(): File exists

**Comment by Neeke** [comment]
可否方便注明版本和环境？谢谢

**Comment by Code-Ken** [comment]
PHP 7.0.11    Linux hi-prod-24 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Neeke** [comment]
缩短目录生成路径，加快创建目录步骤，减少冲突可能。

**Comment by bearzlh** [comment]
@Code-Ken 这个问题有可以重现的具体操作流程吗，或者提供个demo

**Comment by shiftwinting** [comment]
windows php7.3.4nts

php.ini 配置：
[SeasLog]
extension=seaslog.dll
seaslog.use_buffer = 0
seaslog.buffer_size = 100
seaslog.buffer_disabled_in_cli = 0
seaslog.trace_notice = 0
seaslog.trace_warning = 0
seaslog.trace_error = 0
seaslog.trace_exception = 0
seaslog.default_basepath=F:/code/sealog 
seaslog.default_logger = "default"
seaslog.default_template = "%T ||| %L ||| %P ||| %Q ||| %t ||| %M"
seaslog.level = 8
seaslog.throw_exception = 1
seaslog.appender_retry = 5


php测试代码：index.php
SeasLog::setBasePath(dirname(__FILE__).'/logs');
try {
    $path = 'mq_consume_msg' . DIRECTORY_SEPARATOR . date('Y') . DIRECTORY_SEPARATOR . rand(1, 20);
    SeasLog::log(6, 'sssd', [], $path);
} catch (Exception $e) {
    file_put_contents(dirname(__FILE__)."/1.log", "code[".$e->getCode()."]message[".$e->getMessage()."]".PHP_EOL, FILE_APPEND);
}

使用压测工具测试：rsb -n 500 -l -c 20 http://localhost/index.php

会出现：SeasLog Invalid Log File 或  File exists

还有出现：日志内容，中间有空行或者 出现 两行的数据，被合并到一行（错乱）
