### ISSUE TITLE
 SeasLog::setDatetimeFormat()不起作用

### ISSUE THREAD

**Issue by ms100** [SeasX/SeasLog#140]
SeasLog::setDatetimeFormat('m-d H:i:s');
ini_set('seaslog.default_datetime_format','Y-m-d H:i:s');
都显示成功设置，但是不起作用

**Comment by Neeke** [comment]
请注明，什么版本，什么环境，谢谢

**Comment by Neeke** [comment]
不要使用 `SeasLog::setDatetimeFormat('m-d H:i:s'); `将不生效，因为在请求开始时，`default_datetime_format`已经被赋值给`current_datetime_format`，最终使用的是 `current_datetime_format`。

使用`SeasLog::setDatetimeFormat('m-d H:i:s');`是正确的。
这将改变`current_datetime_format`的值。
出于性能考虑，时间格式的改变将被缓存一秒钟，也就是一秒钟后将生效，在调用`setDatetimeFormat`时应该立刻改变这一秒钟的缓存，这是一个Bug，目前已修复。
