### ISSUE TITLE
开启以后fpm就挂了

### ISSUE THREAD

**Issue by yaowenqiang** [SeasX/SeasLog#146]
dmesg:
 [ 7666.422923] php-fpm7.1[4450]: segfault at 10 ip 00007f0c7c3b1fe0 sp 00007ffd7a1feaf0 error 4 in seaslog.so[7f0c7c3ac000+8000]
fph log
[21-Aug-2017 07:58:24] WARNING: [pool www] child 4450 exited on signal 11 (SIGSEGV - core dumped) after 538.621557 seconds from start
vagrant@homestead:/var/log$ php -v
PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )

SeasLog

SeasLog support	Enabled
SeasLog Version	1.6.9
SeasLog Author	Chitao.Gao [ neeke@php.net ]
SeasLog Supports	https://github.com/Neeke/SeasLog
Directive	Local Value	Master Value
seaslog.appender	1	1
seaslog.buffer_size	0	0
seaslog.default_basepath	/var/log/www	/var/log/www
seaslog.default_datetime_format	Y:m:d H:i:s	Y:m:d H:i:s
seaslog.default_logger	default	default
seaslog.disting_by_hour	Off	Off
seaslog.disting_type	Off	Off
seaslog.level	0	0
seaslog.remote_host	127.0.0.1	127.0.0.1
seaslog.remote_port	514	514
seaslog.trace_error	On	On
seaslog.trace_exception	Off	Off
seaslog.use_buffer	Off	Off

**Comment by Neeke** [comment]
您好，可否加群详聊  
QQ群 312910117
