### ISSUE TITLE
是否可以支持修改log目录文件格式

### ISSUE THREAD

**Issue by freenux** [SeasX/SeasLog#150]
log记录目录 = basePath / logger / {fileName}.log
可以设置为这种格式：
log记录目录 = basePath /logger_{fileName}.log

**Comment by Neeke** [comment]
暂不支持。
以目录来区分logger，不方便吗？

**Comment by freenux** [comment]
基于目录的logger不方便日志备份

**Comment by Neeke** [comment]
在备份上面并没有什么差别啊
下一个版本会支持log目录文件格式的自定义的。

**Comment by Neeke** [comment]
将与问题 #172  一起修复
