### ISSUE TITLE
Segfault in 1.7.5

### ISSUE THREAD

**Issue by remicollet** [SeasX/SeasLog#152]
```
$ gdb php
(gdb) run -n -d extension=seaslog.so --re seaslog
...
Program received signal SIGSEGV, Segmentation fault.
0x00005555557901d0 in _zval_ptr_dtor ()

(gdb) bt
#0  0x00005555557901d0 in _zval_ptr_dtor ()
#1  0x00007fffecb38176 in seaslog_clear_request_variable () at /usr/src/debug/php-pecl-seaslog-1.7.5/NTS/src/Request.c:186
#2  zm_deactivate_seaslog (type=<optimized out>, module_number=<optimized out>) at /usr/src/debug/php-pecl-seaslog-1.7.5/NTS/seaslog.c:258
#3  0x00005555557a78c4 in zend_deactivate_modules ()
#4  0x000055555573e985 in php_request_shutdown ()
#5  0x0000555555837303 in do_cli ()
#6  0x000055555561fb79 in main ()
```

**Comment by Neeke** [comment]
What's your version of PHP?

**Comment by remicollet** [comment]
PHP 7.0.23

BTW, fixed by #151 

"SUDO_COMMAND" (used in "cli" case) is probably wrong,

**Comment by remicollet** [comment]
> What's your version of PHP?

Same segfault with 5.4.45, 5.5.38, 5.6.31, 7.0.23, 7.1.9, 7.2.0RC2

**Comment by Neeke** [comment]
I'll fix the problem right now.

**Comment by remicollet** [comment]
Do you plan a quick 1.7.6 ? (or do I build using "master" ?)

**Comment by Neeke** [comment]
Please rebuild test using https://github.com/Neeke/SeasLog/tree/branch_1.7.6
thanks a lot

**Comment by remicollet** [comment]
Yes, master or branch_1.7.6 fix this issue.

Quesiton is "Do you plan a quick 1.7.6 ?" or do I build 1.7.5 + patches for my repository [1] to distribute working packages ?

[1] => https://blog.remirepo.net/pages/PECL-extensions-RPM-status

**Comment by Neeke** [comment]
Please build 1.7.5 + patches.
And my quesiton is, can i re upload the pecl release package by 1.7.5 ?
if i can re upload release package, you can rest it now, and i will re do upload right now.

**Comment by remicollet** [comment]
You can delete the release, and upload it again, but THIS IS A TERRIBLE IDEA, please bump release to 1.7.6

**Comment by Neeke** [comment]
All right, i will plan a quick 1.7.6.
Thanks again.
