### ISSUE TITLE
有没有办法自定义文件名和行号？

### ISSUE THREAD

**Issue by aiwhj** [SeasX/SeasLog#155]
想单独把日志记录抽离出来，然后记录的就只能是当前的文件和行号了

**Comment by Neeke** [comment]
将提供一个配置，指定回溯的层级。
在下个版本修复

**Comment by aiwhj** [comment]
是不是当配置回溯层级为n的时候，在Request.c的220行左右调用n次`ptr->prev_execute_data;`

**Comment by Neeke** [comment]
@aiwhj  没错。已经看到了你的PR，请注意回归测试。

**Comment by aiwhj** [comment]
@Neeke 回归测试就是把tests下的测试用例对吧，还要其他测试用例么
