### ISSUE TITLE
我写的%M不会正确的输出信息而是被替换为了%L(日志等级)

### ISSUE THREAD

**Issue by buffge** [SeasX/SeasLog#156]
我开启了以type分文件,那么日志是这样的文件 2017930.debug|notice|....log 
我根本不需要在文件中显示%L(日志等级).所以我设置日志模版为 "%I | %m | %M | %T | %D%R%F "
当我调用 SeasLog::log('debug', '你好呀');
2017930.debug.log生成日志为:127.0.0.1 | GET | debug | 2017-09-30 20:16:13 | test.com:81/index.php:41 
其中的%M没有正确输出.变成了日志等级.

**Comment by Neeke** [comment]
模板中未定义级别，即%L，定义上即可。
目前有一个小问题，即需要在模板中定义级别。将在下一个版本修复。
