### ISSUE TITLE
希望写TCP/UDP的配置能够再再再详细一些

### ISSUE THREAD

**Issue by codesway** [SeasX/SeasLog#164]
之前从php4log升级到SeasLog中遇到一点关于写TCP/UDP的小尴尬
1.希望SeasLog的配置能够更详细一些，包括配置日志级别和报警多邮箱多级别这块
2.希望能出一套服务端对应的配置，不限于syslog
3.如果能加一分和ELK搭配的方案就更好了。
辛苦涛哥！！！

**Comment by Neeke** [comment]
日志收集的配置和建议
https://github.com/SeasX/SeasLog/blob/master/Specification/SeasLog_Rsyslog_ELK_zh.md
