### ISSUE TITLE
支持PHP7.1.8版本吗

### ISSUE THREAD

**Issue by dusong0717** [SeasX/SeasLog#167]
需要部署到PHP7.1.8版本，使用此扩展

**Comment by dusong0717** [comment]
PHP7.1.8版本 cli下写入文件失败

**Comment by Neeke** [comment]
@dusong0717   请问您使用的SeasLog版本号，以及使用的SeasLog配置项，能否在这里提供，谢谢。

**Comment by dusong0717** [comment]
具体配置

; Enable seasLog extension module

[SeasLog]
;configuration for php SeasLog module
extension = seaslog.so

;Default Log Base Path
seaslog.default_basepath = "/data/logs/seaslog"

;Default Logger Path
seaslog.default_logger = "app"

;The DateTime Style.  Default "Y-m-d H:i:s"
seaslog.default_datetime_format = "Y-m-d H:i:s"

;Default Log template.
;Default "%T | %L | %P | %Q | %t | %M"
seaslog.default_template = "%M"

;Switch use the logger with type.
;1-Y 0-N(Default)
seaslog.disting_type = 0

;Switch use the logger with hour.
;1-Y 0-N(Default)
seaslog.disting_by_hour = 0

;Switch use the log buffer with memory.
;1-Y 0-N(Default)
seaslog.use_buffer = 0

;The buffer size
seaslog.buffer_size = 100

;Record logger level.
;0-EMERGENCY 1-ALERT 2-CRITICAL 3-ERROR 4-WARNING 5-NOTICE 6-INFO 7-DEBUG 8-ALL
;Default 8 (All of them).
;
;   Tips: The configuration item has changed since the 1.7.0 version.
;   Before the 1.7.0 version, the smaller the value, the more logs are taken according to the level:
;   0-all 1-debug 2-info 3-notice 4-warning 5-error 6-critical 7-alert 8-emergency
;   Before the 1.7.0 version, Default 0 (All of them).
seaslog.level = 8

;Automatic Record final error with default logger.
;1-Y(Default) 0-N
seaslog.trace_error = 1

;Automatic Record exception with default logger.
;1-Y 0-N(Default)
seaslog.trace_exception = 0

;Switch the Record Log Data Store.
;1File 2TCP 3UDP (Switch default 1)
seaslog.appender = 1

;If you use  Record TCP or UDP, configure this remote ip.
;Default "127.0.0.1"
seaslog.remote_host = "127.0.0.1"

;If you use Record TCP or UDP, configure this remote port.
;Default 514
seaslog.remote_port = 514

;Trim the \n and \r in log message.
;1-On 0-Off(Default)
seaslog.trim_wrap = 0

;Switch throw SeasLog exception.
;1-On(Default) 0-Off
seaslog.throw_exception = 1

;Switch ignore SeasLog warning.
;1-On(Default) 0-Off
seaslog.ignore_warning = 1

**Comment by dusong0717** [comment]
此问题，已和作者私下沟通解决，很细心解决问题，👍

**Comment by Neeke** [comment]
接下来感受SeasLog给大家带来的超棒体验吧！
