### ISSUE TITLE
提供日志名模板，支持自定义日志名

### ISSUE THREAD

**Issue by Neeke** [SeasX/SeasLog#172]

**Comment by wujunze** [comment]
是要像日志模板一样 让用户可配置的自定义日志文件名?

**Comment by Neeke** [comment]
@wujunze  是的

**Comment by Neeke** [comment]
@wujunze   为保持配置简洁，拟采用：
增加配置项disting_folder,默认为on，此时保持原行为，日志将打在logger/20180211.log或logger/20180211.ERROR.log中；
如果disting_folder被设置为off，此时日志将打在 logger_20180211.log 或 logger_20180211.ERROR.log中

**Comment by linlifu** [comment]
请问如何自定义日志文件名呢?

**Comment by 769344359** [comment]
@linlifu  你想要哪种自定义日志文件名,可以举个例子吗?
根据你的logger 的名字来确定日志文件的路径

**Comment by linlifu** [comment]
比如我想把日志文件名设为abc.log, 路径是/www/app/log/{date}/abc.log, date是当天日期, 是否可以

**Comment by 769344359** [comment]
目前只支持 `<logger_name>[/]<date>.log` 
这种格式的，可以选项是否用logger_name 生成目录,
还不支持用date来做目录的区分
@linlifu 
目前讨论怎么实现一个通用的方案

**Comment by linlifu** [comment]
明白了, 谢谢, 希望能早日实现这个 **自定义日志文件名** 功能

**Comment by Neeke** [comment]
Fixed at 2.2.0
