### ISSUE TITLE
我希望记录日志所在行的行号,但是又想重写log()方法,能不能实现?

### ISSUE THREAD

**Issue by GarenGoh** [SeasX/SeasLog#179]
记录行号的好处是能快速的找到出问题的地方;但是我有需要封装log($level, $message, array $content = array(), $module = '') ,因为我并不知道log的是数组,对象还是字符串.并且还要记录当前用户的id,以及其他逻辑处理. 但是封装后显示的行号都已一样的(封装后调用log()方法得那一行)

**Comment by aiwhj** [comment]
可以试一下**开发版**分支 `bug_fix`，增加了 `seaslog.recall_depth` 回溯层级，可以根据你的 your_log 函数封装的层级进行设置，下个正式版将添加

**Comment by GarenGoh** [comment]
谢谢
