### ISSUE TITLE
能否在代码中，临时更换日志模板？

### ISSUE THREAD

**Issue by JZLeung** [SeasX/SeasLog#180]
如普通模板我只需要 IP，但是 调试模板我需要完整的 URI ，但是现在貌似不能在 PHP 代码中修改模板。

**Comment by Neeke** [comment]
暂不提供临时模板功能。IP、URI等预设变量是在请求初始化时已经获取，并不会影响打日志时的性能，因此请直接使用配置中的模板，谢谢。
