### ISSUE TITLE
cenos 6.5 将seaslog升级到1.7.6报错

### ISSUE THREAD

**Issue by huangcz** [SeasX/SeasLog#182]
错误信息：
`php-fpm[20343]: segfault at 0 ip 00007f2bec7935fd sp 00007ffc6abd3a80 error 4 in seaslog.so[7f2bec78d000+a000]`

**Comment by Neeke** [comment]
请问能提供具体的PHP版本吗

**Comment by huangcz** [comment]
PHP 7.0.22 (built: Aug 28 2017 14:18:28) ( NTS )

**Comment by Neeke** [comment]
@huangcz  能否拉取bug_fix分支，测一下？

**Comment by huangcz** [comment]
好的，可以，这两天抽时间测一下，请耐心等待。

**Comment by Neeke** [comment]
@huangcz  测试结果如何？

**Comment by huangcz** [comment]
不好意思哈，这两天事比较多，没来得及测，我今天晚上测一下，明天早上给出反馈结果

**Comment by huangcz** [comment]
你好，经过测试，还是报错，错误信息：kernel: php-fpm[24739]: segfault at 0 ip 00007f6ac5592dfd sp 00007ffff30bf3e0 error 4 in seaslog.so[7f6ac558c000+b000]。

**Comment by Neeke** [comment]
@huangcz   方便进一步沟通吗？
QQ群：  312910117
或加我的微信: NeekeGao

**Comment by interestingdev** [comment]
[Thu Mar  1 20:01:45 2018] php-fpm[32695]: segfault at 0 ip 00007f367ee0431d sp 00007ffca75c4e80 error 4 in seaslog.so[7f367edfc000+a000]

centOS 7.2 64位
PHP 7.1
kernel: 3.10.0-327.36.3.el7.x86_64

**Comment by Neeke** [comment]
问题已解决。并通过 @huangcz 的验证。
