### ISSUE TITLE
docker centos6.9 php7.1命令行运行 报错：Segmentation fault

### ISSUE THREAD

**Issue by lfyLEE** [SeasX/SeasLog#190]
php.ini  seaslog.default_template = "%T | %L | %P | %t | %Q | %I | %m | %R | %M"

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe8ac1442 in seaslog_template_formatter ()
    at /root/src/SeasLog/src/TemplateFormatter.c:118
118	/root/src/SeasLog/src/TemplateFormatter.c: No such file or directory.
	in /root/src/SeasLog/src/TemplateFormatter.c
(gdb) quit
A debugging session is active.

	Inferior 1 [process 97] will be killed.

**Comment by Neeke** [comment]
出现错误时，可否在gdb中执行bt获取错误栈？

**Comment by lfyLEE** [comment]
#0  0x00007fffe8ac1442 in seaslog_template_formatter ()
    at /root/src/SeasLog/src/TemplateFormatter.c:118
#1  0x00007fffe8ac421b in seaslog_spprintf.constprop.19 ()
   from /alidata/ysphp/php/lib/php/extensions/no-debug-non-zts-20160303/seaslog.so
#2  0x00007fffe8ac553b in zm_activate_seaslog ()
   from /alidata/ysphp/php/lib/php/extensions/no-debug-non-zts-20160303/seaslog.so
#3  0x0000000000849eb0 in zend_activate_modules ()
    at /root/soft/php-7.1.12/Zend/zend_API.c:2539
#4  0x00000000007e3666 in php_request_startup ()
    at /root/soft/php-7.1.12/main/main.c:1700
#5  0x00000000008ecded in do_cli (argc=3, argv=0x11cc850)
    at /root/soft/php-7.1.12/sapi/cli/php_cli.c:964
#6  0x00000000008edc1a in main (argc=3, argv=0x11cc850)
    at /root/soft/php-7.1.12/sapi/cli/php_cli.c:1381

**Comment by Neeke** [comment]
Fixed with #182

**Comment by lfyLEE** [comment]
是基于master修改的吗？什么时间会合到master呢？

**Comment by Neeke** [comment]
已经合并至Master @lfyLEE
