### ISSUE TITLE
rsyslog接收msg的问题

### ISSUE THREAD

**Issue by suruibuas** [SeasX/SeasLog#195]
centos7下配置模版

$template soaLogFormat,"| info | %msg%\n"
发现写入的日志没有内容
$template soaLogFormat,"| info | %rawmsg%\n"
配置为rawmsg才有内容，但是内容中

| info | <14>1 2018-03-27T20:35:00+08:00 localhost.localdomain soa[6772]: {"TRACE":"201803272035006051","PARENT":0,"URL":"htt

多了一段 <14>1 2018-03-27T20:35:00+08:00 localhost.localdomain soa[6772]: 这个东西

**Comment by Neeke** [comment]
@suruibuas 

<14>1 2018-03-27T20:35:00+08:00 localhost.localdomain soa[6772]
是遵守RFC5424约定，同时增加了SeasLog的特性形成的。
格式为：
<{PRI}>1 {time_RFC3339} {host_name} {logger}[{pid}]: {log_message}

**Comment by aiwhj** [comment]
@suruibuas  你用的什么版本的rsyslog? 很有可能是 rsyslog 的默认模板对 SeasLog 的 log 进行了格式化, 导致 %msg% 没有数据. 
我这边 `rsyslogd 7.6.1`   默认模板是 `RSYSLOG_TraditionalFileFormat`

 %msg% 是 
`Mar 29 15:52:16 whj-desktop default[32380]:[2018-03-29] | INFO | 32380 | 1522309936.392 | 5abc9b305fe58 | local | /bin/bash | test187.php | seaslog: i am cli test seaslog rsyslog`

%rawmsg% 是 
`<14>1 2018-03-29T16:09:39+08:00 whj-desktop default[24165]: 2018-03-29 16:09:39 | INFO | 24165 | 1522310979.132 | 5abc9f432068e | local | /bin/bash | test187.php | seaslog: i am cli test seaslog rsyslog`
