### ISSUE TITLE
简单看了一下，不支持log收集汇总

### ISSUE THREAD

**Issue by charlestang** [SeasX/SeasLog#20]
在我们实际业务场景里，业务机器将近20台，如果log都打在各自服务器的本地，那最后出了问题，还是不知道去哪里查的。最好能将log都通过网络输送到一个固定的服务器，那个服务器能够分模块打印log

**Comment by Neeke** [comment]
Fxied with 1.6.2

支持TCP,UDP数据发送。

**Comment by charlestang** [comment]
都两年了，终于支持了……

**Comment by Neeke** [comment]
感谢理解...

2016-07-19 17:40 GMT+08:00 Charles Tang notifications@github.com:
