### ISSUE TITLE
Replacement for php default error handler

### ISSUE THREAD

**Issue by mhf-ir** [SeasX/SeasLog#204]
How can we replace default php error handler with seaslog, and how to forward logs to fluentd / fluentbit or logstash. This might be helpful for clustering and centralize log solution based on php and seaslog.

**Comment by liyang1009** [comment]
First,if you  want  registering  youself custom error/excption  handler is ok. but seaslog is already  finished this feature which can take over  the php exception and error，and  then  execute SeasLog's exception and SeasLog's error.
If you want turn on this feature please read readme and setting  
```
;Automatic Record notice with default logger
;1-Y 0-N(Default)
seaslog.trace_notice = 0

;Automatic Record warning with default logger
;1-Y 0-N(Default)
seaslog.trace_warning = 0

;Automatic Record final error with default logger. 
;1-Y(Default) 0-N
seaslog.trace_error = 1

;Automatic Record exception with default logger. 
;1-Y 0-N(Default)
seaslog.trace_exception = 1
```
propertities  in  SeasLog.ini and first three propertities affect the forth. 

About the fluentd / fluentbit or logstash  SeasLog was  acheived that，but the document is write by Chinese, we will translate to  English very soon, please waiting for a while.
