### ISSUE TITLE
use_buffer 是不是有什么问题啊

### ISSUE THREAD

**Issue by charlestang** [SeasX/SeasLog#21]
PHP 5.3.13 

seaslog.use_buffer = 1
seaslog.buffer_size = 100

./ab -n 100000 -c 10 http://test.com/testseas_log.php

代码如下：

<?php
$logger = new Seaslog();
$ret =$logger->error('test is a test');

最后打出来300行，我预期是能打出来10万行的……

如果不设置 use_buffer 的话，没什么问题……

性能跟 

error_log('error | 25561 | 1408013704.705 | 2014:08:14 18:55:04 | test is a test' . "\n" , 3, '/tmp/error_log.log');

差不多

**Comment by Neeke** [comment]
感谢反馈.

我会着重对buffer测试一下.

在 2014年8月14日 下午7:34，Charles Tang notifications@github.com写道：

**Comment by Neeke** [comment]
fixed with #23 

bug已处理.欢迎继续试用反馈
