### ISSUE TITLE
日志模板希望可以添加User Agent预设变量，方便识别请求来源是什么客户端

### ISSUE THREAD

**Issue by SparkLee** [SeasX/SeasLog#211]

**Comment by aiwhj** [comment]
很多应用可能没有客户端这一角色， SeasLog 遵循 PSR-3 协议， 可以使用 PSR-3 的占位符 placeholders 定义 User Agent。

**Comment by Neeke** [comment]
经SCG(SeasLog Core Group)成员讨论一致认为，保持SeasLog的简洁，不对日志模板添加UA预设变量。
请 @SparkLee  按照 @aiwhj  的建议使用SeasLog函数中提供的content参数来进行处理。

举例：
```
var_dump(SeasLog::debug('this is a debug, UA => {UserAgent}', array('UserAgent' => array_key_exists('HTTP_USER_AGENT',$_SERVER) ? $_SERVER['HTTP_USER_AGENT'] : '')));
```

**Comment by SparkLee** [comment]
好吧，谢谢各位啦！ 也祝SeasLog越来越好！
