### ISSUE TITLE
Mac下配置 seaslog.trace_exception=1 不起作用？

### ISSUE THREAD

**Issue by ueaner** [SeasX/SeasLog#214]
系统信息：

- macOS 10.13.4
- php 7.1.14
- SeasLog 1.8.4

### seaslog.ini 配置

    [seaslog]
    extension=seaslog.so
    seaslog.default_basepath=/tmp/seaslog
    seaslog.trace_exception = 1

### 测试代码

    <?php

    ini_set('display_errors', 1);
    error_reporting(E_ALL);

    var_dump(ini_get('seaslog.trace_exception'));

    throw new Exception('seaslog catch exception log');

    SeasLog::log(SEASLOG_ERROR, 'this is error message ' . rand(1,100));

### 执行结果

1. `/tmp/seaslog/default/20180508.log` 日志文件，并未记录异常信息。
2. 命令行执行结果

![image](https://user-images.githubusercontent.com/318253/39750005-b62daa08-52e6-11e8-970e-547713417035.png)

**Comment by aiwhj** [comment]
![image](https://user-images.githubusercontent.com/16408168/39996584-8d796810-57b2-11e8-8b94-2dc39cd2ba8e.png)
应该是直接 throw，php的报错吧。

**Comment by ueaner** [comment]
@aiwhj 没明白您的意思，对于问题本身，您似乎需要重新看下问题。

**Comment by ueaner** [comment]
@chenhakim 感谢回复，Linux 下测过这个问题，设置 `seaslog.trace_exception = 1` 可以记录异常信息，这个没问题。 but，`问题在于 Mac 下`，不知您这边有支持的打算吗？

另外配置为 `seaslog.level = 8`，记录所有级别的日志信息。

![image](https://user-images.githubusercontent.com/318253/40153591-0fcf1ec0-59bd-11e8-8f20-dc69994e464a.png)

**Comment by aiwhj** [comment]
这边都没有重现出来，日志正常打印，环境有没有装什么特殊的拓展或者设置了某些配置？

**Comment by ueaner** [comment]
@aiwhj 请问您是在 Mac 下么？没有任何其他特殊配置。

**Comment by wujunze** [comment]
@ueaner   Hello  你的phpinfo()整个信息可以截图看一下?

**Comment by ueaner** [comment]
@wujunze 图片太大，存了一份 [phpinfo.html](http://ueaner.github.io/phpinfo.html) 可以点击查看。

**Comment by ueaner** [comment]
@wujunze 貌似跟 xdebug 有关，启用了 xdebug 就记录不到异常。。。
