### ISSUE TITLE
设置basePath不起作用

### ISSUE THREAD

**Issue by pigfly88** [SeasX/SeasLog#217]
php.ini配置用的是默认log根目录，在项目中通过setBasePath修改：

`SeasLog::setBasePath('./logs');`
`SeasLog::info('test');`

但日志还是保存到默认的log根目录

**Comment by aiwhj** [comment]
在什么样的环境下？PHP版本，系统版本？

**Comment by Rock-520** [comment]
@pigfly88  开发者@aiwhj  已联系你为你处理， 但是由于你长时间未回复， 该issue 关闭了哈， 需要可重开issue，重新分配开发者为你处理
