### ISSUE TITLE
Mac下编译出错，希望能解决，或给个解决方案，c小白期待中

### ISSUE THREAD

**Issue by tinder1024** [SeasX/SeasLog#22]
cc -v显示如下
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix

错误信息如下：
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:392:19: warning: implicit declaration of function '_ck_log_dir' is
      invalid in C99 [-Wimplicit-function-declaration]
    int _ck_dir = _ck_log_dir(_log_path);
                  ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:472:13: warning: implicit declaration of function
      '_seaslog_log_content' is invalid in C99 [-Wimplicit-function-declaration]
        if (_seaslog_log_content(argc,level,message,message_len,HASH_OF(_content),logger,logger_len TSRMLS_CC) == FAILURE) {
            ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:476:13: warning: implicit declaration of function '_seaslog_log' is
      invalid in C99 [-Wimplicit-function-declaration]
        if (_seaslog_log(argc,level,message,message_len,logger,logger_len TSRMLS_CC) == FAILURE) {
            ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:735:17: error: non-void function 'php_strtr_array' should return a
      value [-Wreturn-type]
                return;
                ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:839:9: warning: implicit declaration of function '_check_level' is
      invalid in C99 [-Wimplicit-function-declaration]
    if (_check_level(level TSRMLS_CC) == FAILURE) {
        ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:844:5: warning: implicit declaration of function '_mk_log_dir' is
      invalid in C99 [-Wimplicit-function-declaration]
    _mk_log_dir(_log_path);
    ^
/Users/tinder1024/beequick/test/SeasLog/SeasLog/seaslog.c:854:9: warning: implicit declaration of function '_php_log_ex' is
      invalid in C99 [-Wimplicit-function-declaration]
    if (_php_log_ex(log_info, log_len, log_file_path TSRMLS_CC) == FAILURE) {
        ^
6 warnings and 1 error generated.
make: *_\* [seaslog.lo] Error 1

**Comment by Neeke** [comment]
感谢反馈。
将尽快修复

**Comment by Neeke** [comment]
hi @tinder1024 
可否重新pull得代码，进行一个编译测试？
因为我的开发调试一直在Ubuntu、CentOS进行，目前没有mac，非常感谢。

**Comment by tinder1024** [comment]
pull之后可以编译了。不过有个问题
use_buffer=1时，我把buffer_size设置成2测试了下，貌似之后php-fpm重新启动之后能正常输出一次日志，之后就再也不输出了

**Comment by Neeke** [comment]
OK。
mac的编译问题已处理。

关于buffer_size的bug，@charlestang 已经反馈了issues #21 
此问题关闭，请持续关注issues #21

**Comment by Neeke** [comment]
buffer_size的bug已修复.
欢迎继续试用反馈.
