### ISSUE TITLE
cli下调用多次写日志requestid 相同

### ISSUE THREAD

**Issue by ideamean** [SeasX/SeasLog#221]
如上， 是否可以设置不同的requestid?

**Comment by Neeke** [comment]
可以在想要区分requestId时，生成不同的id，并调用SeasLog:: setRequestID($reqeustId)

**Comment by ideamean** [comment]
判断一下是在cli模式下，扩展自动生成不同的requestid比较好

**Comment by Neeke** [comment]
@ideamean  CLI模式下初始化只有一次，无法进行判断
