### ISSUE TITLE
SeasLog 1.8.5 回归测试

### ISSUE THREAD

**Issue by Neeke** [SeasX/SeasLog#226]
分支： structural_reformat

**Comment by qijinkui** [comment]
1. PHP各版本的NTS模式  测试（自动记录错误，异常等功能），测试结果正常
      
![5 3 9](https://user-images.githubusercontent.com/15358546/44452886-41f1c100-a62a-11e8-9c68-53326205507a.png)
![5 4 49](https://user-images.githubusercontent.com/15358546/44452887-428a5780-a62a-11e8-9af5-aa7c1a57f5af.png)
![5 5 38](https://user-images.githubusercontent.com/15358546/44452888-4322ee00-a62a-11e8-9e47-e20090b5a1a5.png)
![5 6 37](https://user-images.githubusercontent.com/15358546/44452889-43bb8480-a62a-11e8-8981-c74b2d8cfbb0.png)
![7 0 31](https://user-images.githubusercontent.com/15358546/44452890-44541b00-a62a-11e8-8a61-4dae73246ead.png)
![7 1 20](https://user-images.githubusercontent.com/15358546/44452895-461dde80-a62a-11e8-95fb-4efd8e9a257b.png)
![7 2](https://user-images.githubusercontent.com/15358546/44456817-31dedf00-a634-11e8-9d75-15395a928e6e.png)

**Comment by qijinkui** [comment]
2. PHP各版本的ZTS模式 测试（自动记录错误，异常等功能），测试结果正常
      
![5 6 37](https://user-images.githubusercontent.com/15358546/44456692-d4e32900-a633-11e8-93f3-2004555d74e7.png)
![7 0 31](https://user-images.githubusercontent.com/15358546/44456693-d57bbf80-a633-11e8-92fa-3f8531a6a30a.png)
![7 1 21](https://user-images.githubusercontent.com/15358546/44456694-d57bbf80-a633-11e8-8c54-20e08a0820a8.png)
![7 2 9](https://user-images.githubusercontent.com/15358546/44456695-d57bbf80-a633-11e8-85ea-469d069c99e4.png)

**Comment by Neeke** [comment]
1.8.5 测试通过。
