### ISSUE TITLE
生成的日志有最多保留数量的配置吗

### ISSUE THREAD

**Issue by DHCMediWay** [SeasX/SeasLog#233]
类似日志切割的功能

**Comment by Neeke** [comment]
可以通过disting_type区分类型、disting_by_hour按小时拆分日志
目前不支持最多保留数量的配置

可以通过shell自行实现定期删除日志。
该shell后结将放至git库中作为建议项。

**Comment by Neeke** [comment]
@DHCMediWay 

定期删除7天前的日志，命令参考：
find . -type f -mtime +7 | grep -E "\.log$"|xargs rm -f

**Comment by Rock-520** [comment]
@DHCMediWay   对于@Neeke的 回答 是否解决你的问题？  由于issue  为确认时间过长，先关闭了哈， 有需要再重开issue
