### ISSUE TITLE
1.86版本不能查看错误日志

### ISSUE THREAD

**Issue by likelxl** [SeasX/SeasLog#234]
`<?php                                                                                                                                                                                    
SeasLog::error('test error'); 
var_dump(SeasLog::analyzerDetail(SEASLOG_ERROR));` 
sh: 1: ERROR: not found
cat: /data/log/default/**.: No such file or directory
array(0) {
}
1.76版本则无此问题

**Comment by Neeke** [comment]
@likelxl  方便发一下SeasLog的运行配置吗

**Comment by likelxl** [comment]
@Neeke 
[SeasLog]
extension = seaslog.so
seaslog.default_basepath = "/data/log"
seaslog.default_logger = "default"
seaslog.disting_folder = 1
seaslog.disting_type = 1
seaslog.diting_by_hour = 1
seaslog.use_buffer = 1
seaslog.buffer_size = 100
