### ISSUE TITLE
能否增加动态修改预设变量的函数

### ISSUE THREAD

**Issue by amuluowin** [SeasX/SeasLog#240]
在CLI模式下很多预设变量是固定值，但是在使用swoole的时候这些变量值是可以获取到的，例如 Domain:Port，Request URI，Request Method，Client IP等，能否提供一个函数可以动态改变这些值。

**Comment by Neeke** [comment]
拟提供set函数：

SeasLog::setRequestVariable(key,value)

**Comment by anoxia** [comment]
原来setRequestVariable是用来作为这类场景补充的，👍！
