### ISSUE TITLE
Uncaught Exception: SeasLog Invalid Log File -

### ISSUE THREAD

**Issue by reelai** [SeasX/SeasLog#244]
错误日志里有很多SeasLog Invalid Log File -/data/curl/20181029.INFO.log  这种错误，权限啥都是ok的，使用touch手动创建也是可以的，这是什么原因啊？
PHP版本:7.1.11
SeasLog:1.8.6
OS:CentOS Linux release 7.2.1511

**Comment by reelai** [comment]
2018/10/29 07:56:37 [error] 16303#0: *569234 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: SeasLog Invalid Log File - /data/curl/20181029.INFO.log in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0" while reading upstream,

**Comment by aben1188** [comment]
出现同样的问题，请问现在有解决方法了吗？

**Comment by out001a** [comment]
同问
应该是权限的问题～～～

**Comment by aben1188** [comment]
问题解决了：是由于日志目录没有写权限导致的。

**Comment by reelai** [comment]
不可能啊，难道我的云主机ls命令被魔改了？
