### ISSUE TITLE
带有context上下文参数时502

### ISSUE THREAD

**Issue by jadesouth** [SeasX/SeasLog#247]
配置如下图：
![image](https://user-images.githubusercontent.com/22884699/48053900-c9d97700-e1e6-11e8-8692-c26fac3a6493.png)

版本信息如下图:
![image](https://user-images.githubusercontent.com/22884699/48053955-ed9cbd00-e1e6-11e8-8602-4235ba254e32.png)

测试代码如下图：
![image](https://user-images.githubusercontent.com/22884699/48054259-d0b4b980-e1e7-11e8-9529-9f7c192ddc0c.png)

测试1号代码结果如下图：
![image](https://user-images.githubusercontent.com/22884699/48054347-08236600-e1e8-11e8-934a-bbc7d877d614.png)

测试2号和3号代码结果如下图（php_errors.log无错误信息输出）：
![image](https://user-images.githubusercontent.com/22884699/48054458-46208a00-e1e8-11e8-8993-83f78f280213.png)

测试2号和3号代码Nginx日志如下图：

PHP错误配置相关如下图：
![image](https://user-images.githubusercontent.com/22884699/48054766-f3939d80-e1e8-11e8-8707-b25d59762c67.png)

@Neeke

**Comment by jadesouth** [comment]
@Neeke

**Comment by jadesouth** [comment]
@Neeke 大佬，我补充下PHP版本信息

![image](https://user-images.githubusercontent.com/22884699/48059953-7cb0d180-e1f5-11e8-98da-7fd1124cd75f.png)

**Comment by aiwhj** [comment]
这个问题应该跟 #187 是同一个问题，在 V1.8.4 及以后版本已经修复了，可以更新一下新版本试试。@jadesouth

**Comment by Neeke** [comment]
@jadesouth  升级SeasLog到1.8.6，可以解决你的问题。请及时反馈，谢谢

**Comment by jadesouth** [comment]
升级SeasLog到1.8.6，已解决问题。
