### ISSUE TITLE
PHP 5.6.36中使用nginx会返回502

### ISSUE THREAD

**Issue by michealzh** [SeasX/SeasLog#251]

**Comment by michealzh** [comment]
2018/12/14 12:41:28 [error] 2625#0: *223 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: api.xxx.com, request: "GET /xxxx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.xxx.com"

使用的方法为 SeasLog::info('xxx')
去掉记录方法nginx正常了
OS环境:macOS Mojavo

**Comment by Neeke** [comment]
@michealzh  请提供一下SeasLog版本号和配置项

**Comment by michealzh** [comment]
版本号是1.9.1  配置项如下:

```
[seaslog]
seaslog.default_basepath = /usr/local/var/seaslog/
seaslog.default_logger = default
seaslog.disting_type = 1
seaslog.disting_by_hour = 1
seaslog.use_buffer = 1
seaslog.buffer_size = 100
seaslog.level = 0
seaslog.trace_error = 1
seaslog.trace_exception = 0
seaslog.default_datetime_format = "Y:m:d H:i:s"
seaslog.appender = 1
;seaslog.remote_host = 127.0.0.1
;seaslog.remote_port = 514
```

**Comment by Neeke** [comment]
问题已解决。

**Comment by Neeke** [comment]
请更新至版本 2.0.2
