### ISSUE TITLE
1.9.0 调用 setBasePath 报错Symbol not found: _seaslog_log_by_level_common_ex

### ISSUE THREAD

**Issue by crazyhl** [SeasX/SeasLog#252]
具体报错内容 dyld: lazy symbol binding failed: Symbol not found: _seaslog_log_by_level_common_ex

更换到1.8.6 就没有问题

操作系统 mac 10.14.2
php版本 7.2.12

**Comment by Neeke** [comment]
在1.9.1版本中已修复。
