### ISSUE TITLE
SeasLog通过UDP/TCP传递日志信息时带BasePath

### ISSUE THREAD

**Issue by pingguoer** [SeasX/SeasLog#264]
SeasLog通过UDP/TCP传递日志信息时在目标机器中拿到当前机器的BasePath

**Comment by Neeke** [comment]
增加一个basePath的预设变量，变量名为 %B
该变量默认使用seaslog.default_basepath配置值，受setBasePath函数影响。

**Comment by giantwu** [comment]
高总，该功能啥时候能release呢

**Comment by 769344359** [comment]
什么是basePath?

**Comment by 769344359** [comment]
是shell的pwd吗?

**Comment by Neeke** [comment]
增加一个basePath的预设变量，变量名为 %B
已release
