### ISSUE TITLE
文件名能修改吗  

### ISSUE THREAD

**Issue by alu12138** [SeasX/SeasLog#279]

**Comment by alu12138** [comment]
0点的时候，在零点目录，会生成昨天和今天两个文件。

**Comment by 769344359** [comment]
什么意思？

**Comment by alu12138** [comment]
![image](https://user-images.githubusercontent.com/12081203/70015449-5015e780-15b8-11ea-886e-53e843aa2ff9.png)
图上这种，我的意思是这种文件名配置可以指定写死吗？

**Comment by 769344359** [comment]
可以改吧,我晚点看看代码

**Comment by 769344359** [comment]
;默认logger目录
seaslog.default_logger = "default"

应该和你**logger** 名字有关
`seaslog.disting_folder = 1` 开启以目录分文件，即logger以目录区分。当关闭时，logger以下划线拼接时间, 如default_20180211.log。
你可以看看readme

**Comment by alu12138** [comment]
恩，了解了，那就是seaslog.default_logger = "default"，seaslog.disting_folder = 0，默认文件名就是default_Ymd.log这种格式，没法通过配置修改了。我的期望就是自己分目录，然后文件名是固定api.log这种，不过这样也没什么影响。
