### ISSUE TITLE
自定义模板方式是不是必须通过php.ini文件？

### ISSUE THREAD

**Issue by lepig** [SeasX/SeasLog#281]
看了函数列表，好像没有能通过调用方法的方式来实现。 

这样必须重启php-fpm。我怕线上会有问题！！！

**Comment by Neeke** [comment]
模板中的很多变量是在请求初始化的时候获取的预设值，这样设计可以获得更好的性能。
在运行过程中设置模板，会损失相当一部分性能。

建议使用context参数进行扩展。
文档参见：
https://www.php.net/manual/zh/seaslog.info.php

`SeasLog::info('log message from {NAME}',array('NAME' => 'neeke'))`
