### ISSUE TITLE
存储文件名是否可以自定义?

### ISSUE THREAD

**Issue by shiftwinting** [SeasX/SeasLog#289]
目前发现文件名存储: 目录/Y-m-d.log 格式，没有找到对应的方式，不知道如何修改？

**Comment by 769344359** [comment]
>默认的 seaslog.disting_type = 0，如果今天我使用了 SeasLog ，那么将产生最终的log文件：
>LogFile = basePath / logger / 20140218.log
>如果 seaslog.disting_type = 1，则最终的log文件将是这样的三个文件
>>infoLogFile = basePath / logger / 20140218.INFO.log
>>warnLogFile = basePath / logger / 20140218.WARNING.log
>>erroLogFile = basePath / logger / 20140218.ERROR.log



[相关文档](https://github.com/SeasX/SeasLog/blob/master/README_zh.md)

**Comment by 769344359** [comment]
不知道是不是你想要的答案,你想要什么样子的日志路径呢?
@shiftwinting

**Comment by shiftwinting** [comment]
其实需要 Y-m-d.log 可以修改为， mylog.log, 主要是使用计划任务来读取log存储为数据库中。

目前做法都是判断前一天是否有log，有的话，跟当前一块读取。

**Comment by shiftwinting** [comment]
另外一个问题： 就是 PHP默认配置seaslog
运行：
SeasLog::setBasePath(‘root_path’); 
SeasLog::setLogger('mylogger');  会默认产生default目录跟 mylogger目录。

但是 我把SeasLog::setLogger('mylogger'); ，SeasLog::setBasePath(‘root_path’);  此时是没有default 目录。

有没有办法可以控制不需要 default目录，同时PHP配置也不需要修改。 像服务器上面站点有多个系统，一个系统有可能有多个 mylogger 目录。

**Comment by 769344359** [comment]
日志的文件名或者路径总会有时间的,
目前有两个配置项控制生成的文件名的方式

>seaslog.disting_folder = 1 开启以目录分文件，即logger以目录区分。当关闭时，logger以下划线拼接时间, 如default_20180211.log。

>seaslog.disting_type = 1 开启以type分文件，即log文件区分info\warn\erro

可能不支持你想要的效果

**Comment by shiftwinting** [comment]
好的，谢谢。
