### ISSUE TITLE
有没有windows版本的SeasLog

### ISSUE THREAD

**Issue by gyf19** [SeasX/SeasLog#29]
有没有windows版本的SeasLog

**Comment by nly** [comment]
正在测试windows版本

**Comment by Neeke** [comment]
Nice , come on boy

2015-05-12 12:53 GMT+08:00 leandre notifications@github.com:

**Comment by Neeke** [comment]
fixed to 1.2.0

**Comment by gyf19** [comment]
能否直接提供dll文件，谢谢

**Comment by Neeke** [comment]
没有问题。

最近将会发布新版本，发布后，我通知你。

2015-06-27 23:15 GMT+08:00, gyf19 notifications@github.com:

**Comment by nly** [comment]
http://windows.php.net/downloads/pecl/releases/seaslog/1.2.0/

**Comment by Neeke** [comment]
https://pecl.php.net/package/SeasLog/1.2.0/windows
