### ISSUE TITLE
 how to add prefix before log file name?

### ISSUE THREAD

**Issue by pigflying** [SeasX/SeasLog#291]
for examp: HI_20200520.log

**Comment by 769344359** [comment]
the same  as 
https://github.com/SeasX/SeasLog/issues/248
and 
https://github.com/SeasX/SeasLog/issues/289

**Comment by 769344359** [comment]
maybe you can try with this
**first step :** 
in `php,ini`
```
seaslog.disting_folder = 0
```
**second step:**
log message with below  code
```
<?php
SeasLog::setLogger('HI');
```
@pigflying

**Comment by Rock-520** [comment]
We will  provide this new feature in Seaslog-2.3.0 ,  refer to https://github.com/SeasX/SeasLog/blob/master/tests/023.phpt
you can configure  default file prefix   in seaslog.ini , and also  use setFilePrefix function to set ,   or   getFilePrefix function get it .
Thank your suggestion ! @pigflying
