### ISSUE TITLE
php8.0编译

### ISSUE THREAD

**Issue by adangadang** [SeasX/SeasLog#300]
/root/php80/SeasLog/src/ExceptionHook.c: In function ‘seaslog_throw_exception_hook’:
/root/php80/SeasLog/src/ExceptionHook.c:53:5: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type [enabled by default]
     message = zend_read_property(default_ce, exception, "message", sizeof("message")-1, 0, &rv);
     ^
In file included from /www/server/php/80/include/php/main/php.h:35:0,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /root/php80/SeasLog/include/ExceptionHook.h:20,
                 from /root/php80/SeasLog/src/ExceptionHook.c:17:
/www/server/php/80/include/php/Zend/zend_API.h:407:16: note: expected ‘struct zend_object *’ but argument is of type ‘struct zval *’
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/root/php80/SeasLog/src/ExceptionHook.c:54:5: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type [enabled by default]
     file = zend_read_property(default_ce, exception, "file", sizeof("file")-1, 0, &rv);
     ^
In file included from /www/server/php/80/include/php/main/php.h:35:0,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /root/php80/SeasLog/include/ExceptionHook.h:20,
                 from /root/php80/SeasLog/src/ExceptionHook.c:17:
/www/server/php/80/include/php/Zend/zend_API.h:407:16: note: expected ‘struct zend_object *’ but argument is of type ‘struct zval *’
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/root/php80/SeasLog/src/ExceptionHook.c:55:5: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type [enabled by default]
     line = zend_read_property(default_ce, exception, "line", sizeof("line")-1, 0, &rv);
     ^
In file included from /www/server/php/80/include/php/main/php.h:35:0,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /root/php80/SeasLog/include/ExceptionHook.h:20,
                 from /root/php80/SeasLog/src/ExceptionHook.c:17:
/www/server/php/80/include/php/Zend/zend_API.h:407:16: note: expected ‘struct zend_object *’ but argument is of type ‘struct zval *’
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/root/php80/SeasLog/src/ExceptionHook.c:56:5: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type [enabled by default]
     code = zend_read_property(default_ce, exception, "code", sizeof("code")-1, 0, &rv);
     ^
In file included from /www/server/php/80/include/php/main/php.h:35:0,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /root/php80/SeasLog/include/ExceptionHook.h:20,
                 from /root/php80/SeasLog/src/ExceptionHook.c:17:
/www/server/php/80/include/php/Zend/zend_API.h:407:16: note: expected ‘struct zend_object *’ but argument is of type ‘struct zval *’
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/root/php80/SeasLog/src/ExceptionHook.c: In function ‘init_exception_hooks’:
/root/php80/SeasLog/src/ExceptionHook.c:78:38: warning: assignment from incompatible pointer type [enabled by default]
             old_throw_exception_hook = zend_throw_exception_hook;
                                      ^
/root/php80/SeasLog/src/ExceptionHook.c:81:35: warning: assignment from incompatible pointer type [enabled by default]
         zend_throw_exception_hook = seaslog_throw_exception_hook;
                                   ^
/root/php80/SeasLog/src/ExceptionHook.c: In function ‘recovery_exception_hooks’:
/root/php80/SeasLog/src/ExceptionHook.c:91:39: warning: assignment from incompatible pointer type [enabled by default]
             zend_throw_exception_hook = old_throw_exception_hook;

**Comment by Neeke** [comment]
Fixed PR #299
