### ISSUE TITLE
SeasLog 2.0.2无法创建日志文件，报错SeasLog Invalid Log File - \/data\/logs\/api\/2022022409.log.

### ISSUE THREAD

**Issue by tomcaroline** [SeasX/SeasLog#312]
linux，nginx 1.20.2，php7.2，SeasLog 2.*, /data/logs/api已经给了777权限，配置如下

seaslog.default_basepath="/data/logs"
seaslog.default_logger="default"
seaslog.default_template = "%T | %t | %L | %P | %M"
seaslog.disting_type=0
seaslog.disting_by_hour=1
seaslog.buffer_size=100
seaslog.level=8
seaslog.trace_error=1
seaslog.trace_exception=0
seaslog.use_buffer=0

**Comment by Rock-520** [comment]
copy that

**Comment by Rock-520** [comment]
已跟用户私聊， nginx 配置问题，非seaslog 代码问题
