### ISSUE TITLE
/usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode

### ISSUE THREAD

**Issue by yuebin1009** [SeasX/SeasLog#316]
/usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode
PHP 7.4.6 (cli) (built: May 12 2020 08:09:15) ( NTS )

**Comment by yuebin1009** [comment]
有人帮忙分析问题吗
与php7.4版本不兼容吗

**Comment by Rock-520** [comment]
> /usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode PHP 7.4.6 (cli) (built: May 12 2020 08:09:15) ( NTS )

php -m  ，然后复制发一下 @[yuebin1009](https://github.com/yuebin1009)

**Comment by yuebin1009** [comment]
php -m
PHP Warning:&nbsp; PHP Startup: Unable to load dynamic library 'seaslog.so' (tried: /usr/lib64/php/modules/seaslog.so (/usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode), /usr/lib64/php/modules/seaslog.so.so (/usr/lib64/php/modules/seaslog.so.so: undefined symbol: php_json_encode)) in Unknown on line 0
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib


[Zend Modules]
Zend OPcache





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeasX/SeasLog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeasX/SeasLog] /usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode (Issue #316)





  
/usr/lib64/php/modules/seaslog.so: undefined symbol: php_json_encode PHP 7.4.6 (cli) (built: May 12 2020 08:09:15) ( NTS )
  
php -m  ，然后复制发一下

**Comment by Rock-520** [comment]
是不是json 扩展没有安装？  如果有可能是扩展加载顺序的问题，去掉php.ini 中的extension=seaslog.so  改在conf.d中新增文件seaslog.ini ，内容为：extension=seaslog.so

**Comment by yuebin1009** [comment]
> 是不是json 扩展没有安装？ 如果有可能是扩展加载顺序的问题，去掉php.ini 中的extension=seaslog.so 改在conf.d中新增文件seaslog.ini ，内容为：extension=seaslog.so

好的
