### ISSUE TITLE
mac 下的bug

### ISSUE THREAD

**Issue by alongken2005** [SeasX/SeasLog#41]
我设置了
seaslog.default_basepath = /Users/zhanghao/www/logs
seaslog.default_logger = default
但是日志还是只记到/Users/zhanghao/www/logs 目录下，没到default目录下，怎么回事？

用Seaslog::analyzerDetail('all'), 获取到的是空数组，获取不到全部日志
而且我必须先执行下记录的行为才能获取Seaslog::analyzerDetail()的内容，比如必须这样才能获取
Seaslog:debug("test");
$list = Seaslog::analyzerDetail("debug");
这样$list才有内容

单单用$list = Seaslog::analyzerDetail("debug"); $list是空数组
配置如下：
extension = seaslog.so
seaslog.default_basepath = /Users/zhanghao/www/logs    ;默认log根目录
seaslog.default_logger = default                ;默认logger目录
seaslog.disting_type = 1                        ;是否以type分文件 1是 0否(默认)
seaslog.disting_by_hour = 0                     ;是否每小时划分一个文件 1是 0否(默认)
seaslog.use_buffer = 1                          ;是否启用buffer 1是 0否(默认)
seaslog.buffer_size = 10                       ;buffer中缓冲数量 默认0(不使用buffer_size)
seaslog.level = 0                               ;记录日志级别 默认0(所有日志)

seaslog.use_buffer和seaslog.buffer_size = 10 无论怎么设置都一样

**Comment by Neeke** [comment]
问题确认

**Comment by Neeke** [comment]
能否将你的测试脚本在这里备注一份

**Comment by alongken2005** [comment]
我直接执行上面我写的函数啊，你不能重现吗？我是在ci框架里执行的，

**Comment by Neeke** [comment]
Seaslog::analyzerDetail('all')  
这样使用是错误的。   all 不是一个类型

**Comment by alongken2005** [comment]
那要查所有的，只能留空？但是count里你用的是all啊
static public function analyzerCount($level = 'all',$log_path = '*',$key_word = NULL)
    {
        return array();
    }

**Comment by Neeke** [comment]
问题已fix

**Comment by alongken2005** [comment]
效率好高啊，赞一个

**Comment by Neeke** [comment]
测试一下，如无问题，准备明天发新版本 1.2.1

**Comment by alongken2005** [comment]
嗯，晚上回去测，公司没环境

**Comment by Neeke** [comment]
新版本已发布：  https://pecl.php.net/package-changelog.php?package=SeasLog&release=1.2.2
