### ISSUE TITLE
not support for PHP 7.0.0 alpha2

### ISSUE THREAD

**Issue by zhaoxiong123** [SeasX/SeasLog#43]
not support for PHP 7.0.0 alpha2

fatal error: ext/standard/php_smart_str.h: No such file or directory

**Comment by Neeke** [comment]
PHP 7.0.0 目前还不支持
正在开发中

**Comment by linclin** [comment]
PHP 7.0.0正式版编译失败了,啥时候可以支持.项目大量使用了seaslog,现无法迁移到PHP7

**Comment by Neeke** [comment]
将尽快支持。下周将发布。可加群，随时关注动态。

2015-12-03 18:48 GMT+08:00 LC notifications@github.com:

**Comment by Neeke** [comment]
已支持PHP7，请更新至版本 1.5.0
