### ISSUE TITLE
可不可为跑在同一台服务器上的不周项目配置不同的日志级别？ 

### ISSUE THREAD

**Issue by jeffcao** [SeasX/SeasLog#45]
请问，可不可为跑在同一台服务器上的不周项目配置不同的日志级别？ 
如果可以，如何操作？谢谢。

**Comment by Neeke** [comment]
可以.

php.ini中的配置,同样可以放在项目根目录下的.htaccess中

项目根目录下的.htaccess中的配置,会作为当前目录的配置,而不影响php.ini中对整体配置的影响.

**Comment by jeffcao** [comment]
谢了，是的,  已经解决.
