### ISSUE TITLE
 redis server  went  away

### ISSUE THREAD

**Issue by habbyCP** [SeasX/SeasLog#56]
使用phpredis扩展的2.2.3版本 会报这个异常,只是异常,redis 连接 读取 不受影响
升级2.2.5后异常消失.可否向下兼容?

**Comment by Neeke** [comment]
该问题是phpredis扩展2.2.3的一个bug, 该bug已经在phpredis 2.2.4版本中修复,请升级你的phpredis扩展到2.2.4版本或以上.

该bug描述:
https://github.com/phpredis/phpredis/issues/374
