### ISSUE TITLE
是否支持异步，是否支持tcp发送数据

### ISSUE THREAD

**Issue by vus520** [SeasX/SeasLog#59]
需求场景，有多台集群，日志需要统一收集，目前使用写入日志文件的方式，还需要单独再进行日志收集和整理，业务架构比较复杂。

集群中的php如果能把日志发送(异步)到指定的server就比较理想了，参考nginx的access log对rsyslog的支持。

**Comment by Neeke** [comment]
收到需求.

会参考nginx对rsyslog的支持

**Comment by xuebingwang** [comment]
请问这个需求开始开发了吗？ 大概哪个版本会上！是作者太忙了吗，呵呵！

**Comment by Neeke** [comment]
Fixed with 1.6.2

支持TCP,UDP数据发送，请查看支持文档。

**Comment by xuebingwang** [comment]
大赞
