### ISSUE TITLE
开启buffer后，并未生效

### ISSUE THREAD

**Issue by hbclare** [SeasX/SeasLog#60]
执行脚本
    public function testSeasLog(){
        for($i=0; $i<100; $i++){
            SeasLog::error(time());
            sleep(2);  
        }  
    }
测试结果，
tail -n 50 -f error.log
error | 8806 | 1447054160.976 | 2015:11:09 15:29:20 | 1447054160 
error | 8806 | 1447054162.976 | 2015:11:09 15:29:22 | 1447054162 
每2秒增加一条数据

希望结果
error日志中，为空，在程序执行完成后，error日志一次写入

**Comment by vb2005xu** [comment]
蝙蝠哥不能犯这个错误吧,恭喜你 昌老湿

**Comment by Neeke** [comment]
正在确认.

2015-11-09 16:22 GMT+08:00 vb2005xu notifications@github.com:

**Comment by Neeke** [comment]
@hbclare  已经Fixed 请确认
