### ISSUE TITLE
能在你这之上绑忙定制开发一个DEBUG插件吗?

### ISSUE THREAD

**Issue by km3945** [SeasX/SeasLog#66]
能在你这之上绑忙定制开发一个DEBUG插件吗?
QQ1983263.
也许我这需求完成后开源也是个好东西.具体加我,我们聊下.谢谢

**Comment by Neeke** [comment]
具体需求可整理一下，我的联系方式：
email:   neeke@php.net
微信:  NeekeGao

**Comment by Neeke** [comment]
Closed with #67
