### ISSUE TITLE
某些版本php会core dump

### ISSUE THREAD

**Issue by longerpop** [SeasX/SeasLog#74]
当前php版本是php5.3.3 
seaslog 版本 1.5.0
log.php 文件内容为：
Zend Extension Build => API20090626,NTS

``` php
<?php
SeasLog::log(SEASLOG_ERROR,'this is a error test by ::log');
SeasLog::debug('this is a {userName} debug',array('{userName}' => 'neeke'));
?>
```

运行 php log.php 就会core dump .
把use_buffer设置成0就不会出现次现象！但是buffer还是很重要的
在php5.6版本上未出现此问题

**Comment by Neeke** [comment]
5.3.10及以上版本， 该问题并不会重现。

5.3.3的该bug，稍后处理。

**Comment by wgm89** [comment]
php5.6 仍有此bug

**Comment by Neeke** [comment]
是nts或者zts ?

2016-08-01 14:07 GMT+08:00 saeed notifications@github.com:

**Comment by wgm89** [comment]
nts

**php -v** 

PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**配置:**

 Thread Safety  disabled

测试了 seaslog 1.5 ~ 1.6 都有这个问题。

### strace 分析结果:

fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc03c2fe000
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc03c2fd000
lseek(1, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
lseek(2, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
getcwd("/var/www", 4096)                = 9
ioctl(4, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffcae8908a0) = -1 ENOTTY (Inappropriate ioctl for device)
fstat(4, {st_mode=S_IFREG|0644, st_size=528, ...}) = 0
mmap(NULL, 560, PROT_READ, MAP_PRIVATE, 4, 0) = 0x7fc03c2fc000
munmap(0x7fc03c2fc000, 560)             = 0
close(4)                                = 0
munmap(0x7fc03c2ff000, 4096)            = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x14} ---
+++ killed by SIGSEGV +++
[1]    4431 segmentation fault  strace php test.php

**Comment by Neeke** [comment]
ok 收到。

2016-08-02 9:20 GMT+08:00 saeed notifications@github.com:

**Comment by Neeke** [comment]
@longerpop   @wgm89  可否使用Master版本再测试一下，SeasLog版本为 1.6.4
