### ISSUE TITLE
有没有window下的教程？

### ISSUE THREAD

**Issue by feng003** [SeasX/SeasLog#75]
是不是找到相对应php版本的dll文件，放在php文件下面的ext文件，修改一下php.ini 就可以了？

**Comment by phpforlan** [comment]
你好，这个问题你需要从以下步骤着手：

1、查看php.ini文件，找到extension_dir配置项，找到扩展目录位置
2、把下载的SeasLog的dll文件，拷贝到上面的目录中
3、在php.ini中加入一行：extension=seaslog.dll
4、重启php即可生效

**Comment by phpforlan** [comment]
补上一个回答：如何找到正确的SeasLog版本？
1、首先利用phpinfo() 函数，获取当前的php版本，如5.3
2、打开http://pecl.php.net/package/SeasLog/1.4.8/windows，找到对应的dll文件，下载到本地即可。

**Comment by freedomdeity0319** [comment]
@phpforlan 按照你的步骤为什么，我的查看phpinfo，没有找到seaslog扩展，换了5.5的对应扩展和5.6的对应扩展都不行，我的php版本可以调成5.5.25和5.6.9

**Comment by Neeke** [comment]
谢谢 @phpforlan  的回答。
