### ISSUE TITLE
发现一个问题：SeasLog::setBasePath这个不能使用两次，使用两次会挂

### ISSUE THREAD

**Issue by jxy918** [SeasX/SeasLog#79]
发现一个问题：SeasLog::setBasePath这个不能使用两次，使用两次会挂（ERR_EMPTY_RESPONSE）
SeasLog::setBasePath('aaaa');
SeasLog::setBasePath('bbbb');
这个问题有点难发现，而写日志的场景， 的确会会出现， 同时切换到不同路径的情况。

补充：是在apache环境下， 不是必现，重启服务器或断电，就很容易出现这样的情况，有时候重启几次apache又会好， 但是一旦出现页面挂的情况， 调试代码：发现掉了两次 setBasePath方法必挂，去除这个方法，就会好，不断重启apache就会重现上面的问题，ps：我的环境是虚拟机。

测试nginx无此现网发生

**Comment by jxy918** [comment]
补充：是在apache环境下， 不是必现，重启服务器或断电，就很容易出现这样的情况，有时候重启几次apache又会好， 但是一旦出现页面挂的情况， 调试代码：发现掉了两次 setBasePath方法必挂，去除这个方法，就会好

**Comment by Neeke** [comment]
fixed with #80
