### ISSUE TITLE
发现一个\SeasLog::setBasePath、\SeasLog::setLogger 报502问题

### ISSUE THREAD

**Issue by uduemc** [SeasX/SeasLog#80]
PHP7.0.4
SeasLog Version 1.5.0
Nginx 1.4.7
OS Linux CentOS 6.5
如果使用
\SeasLog::setBasePath('PATH/project/log');
不会出现502问题。但是输入的如果是如下：
\SeasLog::setBasePath(\App::path('log'));
带入的参数是一个返回得到的带有 '/' 的路径则页面报 502 错误
\SeasLog::setLogger 同样

**Comment by youmingdot** [comment]
同样的问题，稍微测试了一下，发现在PHP7上会有内存泄漏（其他版本没测过），在某些时候还会导致`Exited on signal 11`，这就让Apache或者Ngnix出现Bad Gateway错误。

**Comment by ghost** [comment]
PHP7.0.5
SeasLog 1.5.3
调用几次 SeasLog::setBasePath 和 SeasLog::log 就会导致 php-fpm 内存泄漏 Segmentation fault 11 退出
