### ISSUE TITLE
请问这是正确的吗？

### ISSUE THREAD

**Issue by 3ugo** [SeasX/SeasLog#83]
PHP 7.0.5
centos 6.6
seaslog 1.5.3
<?php
SeasLog::debug('this is a {userName} debug',array('{userName}' => 'neeke'));

文件里面内容显示是这样：
debug | 29783 | 1461427939.348 | 2016:04:24 01:12:19 | this is a neeke debug

**Comment by Neeke** [comment]
是正确的。{userName}  是占位符。
