### ISSUE TITLE
Conflit with Wincache

### ISSUE THREAD

**Issue by vibbow** [SeasX/SeasLog#89]
OS Version: Windows 10 x64 10.0.10586
PHP Version: PHP 7.0.6 x64 nts, with XDebug 2.4.0 enabled
WinCache version: 2.0.0.6
SeasLog version: 1.5.6

PHP is running in Fast-CGI mode with IIS Server 10.

After I enable WinCache & SeasLog together, and calling WinCache related function, the php-cgi.exe process will crash.

**Comment by Neeke** [comment]
The specific use of the WinCache which way?
