### ISSUE TITLE
windows下格式化时间显示不正确

### ISSUE THREAD

**Issue by iwzh** [SeasX/SeasLog#90]
windows版本下发现格式化的时间并没有显示。

 #seaslog版本1.5.6
 #php版本7.0 

`error | 23625 | 1406422432.786 | Y:m:d H:i:s | this is a log`

**Comment by iwzh** [comment]
补充说明：
php5.5.30
seaslog 1.4.8
环境下。写入正确
error | 29824 | 1466050422.121 | 2016:06:16 12:13:42 | this is a wzh debug

**Comment by Neeke** [comment]
能否看一下 phpinfo页面中 SeasLog加载的配置项是什么？

**Comment by Neeke** [comment]
Fixed with 1.5.8 & 1.6.0
