### ISSUE TITLE
日志内容中时间显示的不对

### ISSUE THREAD

**Issue by artwl** [SeasX/SeasLog#92]
配置：
![1](https://cloud.githubusercontent.com/assets/982563/16214816/b604c1d0-378e-11e6-945b-bd5431fdb36e.png)

结果：
![2](https://cloud.githubusercontent.com/assets/982563/16214820/bb7e8092-378e-11e6-8f54-0da07134fa7a.png)

环境 ubuntu 12.04

**Comment by Neeke** [comment]
Fixed with 1.5.8 & 1.6.0
