### ISSUE TITLE
错误日志只记录一次的bug

### ISSUE THREAD

**Issue by bingo-x** [SeasX/SeasLog#94]
在windows系统下：
apache第一次启动，第一次运行php脚本时，seaslog会记录错误。但是再一次运行php脚本时，seaslog并未写入日志。
当我重启apache后，第一次运行php脚本时，seaslog会记录错误。但是再一次运行php脚本时，又看到seaslog并未写入日志。

此现象出现在记录错误时，记录异常没有这样的现象。

Linux系统下记录错误正常。

windows环境：PHP5.6.22，seaslog1.4.8
Linux环境：PHP5.6.16，seaslog1.4.8

**Comment by Neeke** [comment]
1.4.8 之后版本，该问题已修复。
