### ISSUE TITLE
1.5.6 does not output log with the php 7.0.8 on ubuntu 16

### ISSUE THREAD

**Issue by laomagege** [SeasX/SeasLog#95]
/var/www/html/seaslog.test.php:31:
array (size=8)
  'debug' => int 0
  'info' => int 0
  'notice' => int 0
  'warning' => int 0
  'error' => int 0
  'critical' => int 0
  'alert' => int 0
  'emergency' => int 0
/var/www/html/seaslog.test.php:32:
array (size=0)
  empty
/var/www/html/seaslog.test.php:33:
array (size=0)
  empty
/var/www/html/seaslog.test.php:34:string 'test/logger' (length=11)
/var/www/html/seaslog.test.php:37:null

**This is the output of seaslog.test.php, seemed the message string does not pass to the php module.**

**Comment by Neeke** [comment]
would you use release 1.6.0 to make a test again?

**Comment by Neeke** [comment]
Fixed with 1.6.2
