### ISSUE TITLE
在ubuntu下使用不能使用SeasLog

### ISSUE THREAD

**Issue by Walk-Code** [SeasX/SeasLog#99]
http://ww4.sinaimg.cn/large/005yEbTbgw1f5to6sxpssj30ht00zmxe.jpg
通过phpinfo()可以找到SeasLog.我是通过PECL安装的.
谢谢.

**Comment by Walk-Code** [comment]
已解决

**Comment by Neeke** [comment]
If you use namespace, you should write such as "\SeasLog::info('msg')".
